DROP SCHEMA MCRONALDS_DB;
CREATE SCHEMA MCRONALDS_DB;
USE MCRONALDS_DB;
CREATE TABLE RESTAURANT_T(
	RestaurantID INTEGER NOT NULL,
    Address VARCHAR(30),
    City VARCHAR(20),
    State CHAR(2),
    ZipCode VARCHAR(10),
    SalesTax DECIMAL,
    ManagerID INTEGER,
    CONSTRAINT RESTAURANT_PK PRIMARY KEY (RestaurantID)
);
CREATE TABLE EMPLOYEE_T(
	EmployeeID INTEGER NOT NULL,
    Name VARCHAR(25),
    Address VARCHAR(30),
    City VARCHAR(20),
    State CHAR(2),
    ZipCode VARCHAR(10),
    Phone VARCHAR(10),
    Email VARCHAR(30),
    SSN VARCHAR(10),
    Birthday DATE,
    EmployeeType VARCHAR(15),
    RestaurantID INTEGER NOT NULL,
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EmployeeID)
);
CREATE TABLE PARTTIME_T(
	EmployeeID INTEGER NOT NULL,
    HourlyRate DECIMAL,
    CONSTRAINT PARTTIME_PK PRIMARY KEY(EmployeeID)
);
CREATE TABLE FULLTIME_T(
	EmployeeID INTEGER NOT NULL,
    AnnualSalary DECIMAL,
    CONSTRAINT FULLTIME_PK PRIMARY KEY(EmployeeID)
);
CREATE TABLE CUSTOMER_T(
	CustomerID INTEGER NOT NULL,
    Name VARCHAR(20),
    CONSTRAINT CUSTOMER_PK PRIMARY KEY(CustomerID)
);
CREATE TABLE ORDER_T(
	OrderID INTEGER NOT NULL,
    OrderDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    SalePrice DECIMAL,
    RestaurantID INTEGER NOT NULL,
    CONSTRAINT ORDER_PK PRIMARY KEY(OrderID)
);
CREATE TABLE RECEIPT_T(
	OrderID INTEGER NOT NULL,
    CustomerID INTEGER NOT NULL,
    CONSTRAINT RECEIPT_PK PRIMARY KEY(OrderID, CustomerID)
);
CREATE TABLE ITEM_T(
	ItemID INTEGER NOT NULL,
    Description VARCHAR(100),
    Size VARCHAR(10),
    Price DECIMAL,
    CONSTRAINT ITEM_PK PRIMARY KEY(ItemID)
);
CREATE TABLE ORDERLINE_T(
	OrderID INTEGER NOT NULL,
    ItemID INTEGER NOT NULL,
    OrderedQuantity INTEGER,
    CONSTRAINT ORDERLINE_PK PRIMARY KEY(OrderID, ItemID)
);

ALTER TABLE RESTAURANT_T ADD FOREIGN KEY (ManagerID) REFERENCES FULLTIME_T(EmployeeID);
ALTER TABLE EMPLOYEE_T ADD FOREIGN KEY (RestaurantID) REFERENCES RESTAURANT_T(RestaurantID);
ALTER TABLE PARTTIME_T ADD FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE_T(EmployeeID);
ALTER TABLE FULLTIME_T ADD FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE_T(EmployeeID);
ALTER TABLE ORDER_T ADD FOREIGN KEY (RestaurantID) REFERENCES RESTAURANT_T(RestaurantID);
ALTER TABLE RECEIPT_T ADD FOREIGN KEY (OrderID) REFERENCES ORDER_T(OrderID);
ALTER TABLE RECEIPT_T ADD FOREIGN KEY (CustomerID) REFERENCES CUSTOMER_T(CustomerID);
ALTER TABLE ORDERLINE_T ADD FOREIGN KEY (OrderID) REFERENCES ORDER_T(OrderID);
ALTER TABLE ORDERLINE_T ADD FOREIGN KEY (ItemID) REFERENCES ITEM_T(ItemID);